CREATE TABLE Users (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    balance DECIMAL(12,2) DEFAULT 0.00 NOT NULL,
    CHECK(balance >= 0)
);

CREATE TABLE Products (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    category VARCHAR(255) NOT NULL,
    description VARCHAR(511) NOT NULL,
    price DECIMAL(12,2) NOT NULL CHECK(price >= 0),
    image VARCHAR(255) NOT NULL
);

CREATE TABLE Sellers (
    id INT NOT NULL PRIMARY KEY REFERENCES Users(id)
);

CREATE TABLE Tags (
    product_id INT NOT NULL REFERENCES Products(id),
    tag VARCHAR(255) NOT NULL,
    PRIMARY KEY(product_id,tag)
);

CREATE TABLE Inventory (
    product_id INT NOT NULL REFERENCES Products(id),
    seller_id INT NOT NULL REFERENCES Sellers(id),
    quantity INT NOT NULL CHECK (quantity >= 0),
    PRIMARY KEY(product_id, seller_id)
);

CREATE TABLE CartEntries (
    user_id INT NOT NULL,
    seller_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    price_per_unit DECIMAL(12,2) NOT NULL,
    is_saved_for_later BOOLEAN DEFAULT FALSE NOT NULL,
    PRIMARY KEY(user_id, seller_id, product_id),
    CHECK(user_id <> seller_id),
    CHECK(quantity > 0)
);

CREATE TABLE Orders (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL REFERENCES Users(id),
    user_address VARCHAR(255) NOT NULL,
    order_total DECIMAL(12,2) NOT NULL CHECK (order_total >= 0),
    datetime timestamp without time zone NOT NULL,
    order_fulfilled_datetime timestamp without time zone
);

CREATE TABLE Purchases (
    order_id INT NOT NULL REFERENCES Orders(id),
    seller_id INT NOT NULL REFERENCES Sellers(id),
    product_id INT NOT NULL REFERENCES Products(id),
    quantity INT NOT NULL CHECK (quantity > 0),
    price_per_unit DECIMAL(12,2) NOT NULL,
    item_fulfilled_datetime timestamp without time zone,
    PRIMARY KEY(order_id, seller_id, product_id)
);

CREATE TABLE ProductReviews (
    user_id INT NOT NULL REFERENCES Users(id),
    seller_id INT NOT NULL REFERENCES Sellers(id),
    product_id INT NOT NULL REFERENCES Products(id),
    description VARCHAR(511),
    rating INT NOT NULL CHECK (rating > 0 AND rating < 6),
    upvotes INT CHECK (upvotes >= 0),
    datetime timestamp without time zone NOT NULL,
    filename VARCHAR(255),
    CHECK (user_id <> seller_id),
    PRIMARY KEY(user_id, product_id, seller_id)
);

CREATE TABLE SellerReviews (
    user_id INT NOT NULL REFERENCES Users(id),
    seller_id INT NOT NULL REFERENCES Sellers(id),
    description VARCHAR(511),
    rating INT NOT NULL CHECK (rating > 0 AND rating < 6),
    upvotes INT CHECK (upvotes >= 0),
    datetime timestamp without time zone NOT NULL,
    CHECK (user_id <> seller_id),
    PRIMARY KEY(user_id, seller_id)
);